apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess.fullname" . }}-app
  labels:
    {{- include "chess.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
